# Generated by Django 6.0.3 on 2026-03-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название объявления', max_length=255, verbose_name='Заголовок')),
                ('price', models.IntegerField(help_text='Общая стоимость квартиры', verbose_name='Цена ($)')),
                ('price_per_m2', models.FloatField(blank=True, help_text='Цена за квадратный метр', null=True, verbose_name='Цена за м²')),
                ('rooms', models.IntegerField(blank=True, help_text='Количество комнат', null=True, verbose_name='Комнаты')),
                ('area', models.FloatField(blank=True, help_text='Общая площадь квартиры', null=True, verbose_name='Площадь (м²)')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажей всего')),
                ('city', models.CharField(default='Бишкек', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('address', models.TextField(help_text='Полный адрес объявления', verbose_name='Адрес')),
                ('source', models.CharField(choices=[('house', 'House.kg'), ('lalafo', 'Lalafo.kg')], max_length=10, verbose_name='Источник')),
                ('link', models.URLField(help_text='Ссылка на объявление', unique=True, verbose_name='Ссылка')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Собственник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('house', 'House.kg'), ('lalafo', 'Lalafo.kg')], max_length=10, verbose_name='Источник')),
                ('message', models.TextField(help_text='Текст ошибки или события', verbose_name='Сообщение')),
                ('is_error', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог парсера',
                'verbose_name_plural': 'Логи парсера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Произвольное имя настройки (например: '2-комн Магистраль')", max_length=100, verbose_name='Название настройки')),
                ('discount_percent', models.FloatField(default=20, help_text='На сколько процентов цена должна быть ниже рынка (например: 20)', verbose_name='Процент ниже рынка')),
                ('min_rooms', models.IntegerField(blank=True, help_text='Минимальное количество комнат (например: 1)', null=True, verbose_name='Минимум комнат')),
                ('max_rooms', models.IntegerField(blank=True, help_text='Максимальное количество комнат (например: 3)', null=True, verbose_name='Максимум комнат')),
                ('district', models.CharField(blank=True, help_text='Фильтр по району (например: Магистраль)', max_length=100, null=True, verbose_name='Район')),
                ('is_active', models.BooleanField(default=True, help_text='Включена ли эта настройка', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Настройка парсера',
                'verbose_name_plural': 'Настройки парсера',
            },
        ),
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Ссылка на изображение квартиры', verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parser_functions.flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Изображение квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(verbose_name='Комнаты')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('avg_price_per_m2', models.FloatField(verbose_name='Средняя цена за м²')),
                ('median_price_per_m2', models.FloatField(help_text='Более точный показатель рынка', verbose_name='Медианная цена за м²')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика рынка',
                'verbose_name_plural': 'Статистика рынка',
                'unique_together': {('rooms', 'district')},
            },
        ),
    ]
