# Generated by Django 5.2.9 on 2026-03-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_functions', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='parser_functions.flat', verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_flats', to='user.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленная квартира',
                'verbose_name_plural': 'Отправленные квартиры',
                'indexes': [models.Index(fields=['user', 'flat'], name='parser_func_user_id_2d6e37_idx')],
                'unique_together': {('user', 'flat')},
            },
        ),
    ]
