# Generated by Django 6.0.3 on 2026-03-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Ссылка на изображение квартиры', verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parser_functions.flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Изображение квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
    ]
