# Generated by Django 5.2.9 on 2026-03-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], db_index=True, default='website', help_text='Источник, с которого поступил чат (сайт, Telegram, WhatsApp).', max_length=20, verbose_name='Платформа')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Идентификатор чата во внешней системе (например, telegram_id или session_id).', max_length=255, null=True, verbose_name='Внешний ID')),
                ('language', models.CharField(blank=True, help_text='Язык общения в чате в формате ISO 639-1 (например: ru, en, ky).', max_length=16, null=True, verbose_name='Язык')),
                ('messages_cache', models.JSONField(blank=True, default=list, help_text='JSON-список последних сообщений для быстрой передачи в LLM без запроса к БД.', verbose_name='Кэш сообщений')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(blank=True, help_text='Зарегистрированный пользователь, которому принадлежит чат. Может быть пустым для гостей.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], help_text='Роль отправителя: user — пользователь, assistant — ИИ, system — системный промпт.', max_length=16, verbose_name='Роль')),
                ('text', models.CharField(help_text='Текст сообщения. Максимум 5000 символов.', max_length=5000, verbose_name='Текст')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Произвольные метаданные: токены, модель, latency и т.д.', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('chat', models.ForeignKey(help_text='Чат, к которому относится данное сообщение.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_type', 'created_at'], name='chat_chat_chat_ty_a591ef_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'chat_type'], name='chat_chat_user_id_5e059e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'role'], name='chat_messag_chat_id_db64d8_idx'),
        ),
    ]
